### ISSUE TITLE
Still using ganfra's package name. 

### ISSUE THREAD

**Issue by peterbetos** [smtchahal/MaterialSpinner#1]
Hi, it seems that you're still using the ganfra package paths on your aar. Can you check? 

Please see my exploded aar screenshot:
![screen shot 2016-07-21 at 2 20 03 pm](https://cloud.githubusercontent.com/assets/3241327/17013140/e2fbbb30-4f4e-11e6-8a32-f551399d9b1b.png)

**Comment by peterbetos** [comment]
Found the culprit. The readme still says 1.1.3. Kindly update the readme. Thanks.

**Comment by peterbetos** [comment]
Please correct the layout xml class name as well please. It's generated as <smtchahal.materialspinner.MaterialSpinner

**Comment by smtchahal** [comment]
Just upgraded the library to version 1.1.5 with an updated README.md (no changes, just another version bump for jitpack's sake). Please check again, and sorry for the mess!

**Comment by peterbetos** [comment]
Thanks @smtchahal. Great as always 👍
