### ISSUE TITLE
onItemSelected returns the position of the first legitimate spinner item as -1

### ISSUE THREAD

**Issue by peterbetos** [smtchahal/MaterialSpinner#2]
It seems that the first legit spinner item (after the hint item) is returned as -1 on the onItemSelected override. Please check. Thanks.

**Comment by peterbetos** [comment]
The issue is also affecting the ms_floatingLabelText. Selecting hint has no floatingLabelText reaction, selecting the 1st spinner item makes it disappear.

**Comment by smtchahal** [comment]
Are you referring to the `getSelectedItemPosition` method?

**Comment by peterbetos** [comment]
Not really, on this override: 
public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {}

the one that you set on materialsprinner.setOnItemSelectedListener()

**Comment by smtchahal** [comment]
Did this problem exist *before* I forked the project? I'm trying to figure out if it was my changes that broke something.

**Comment by peterbetos** [comment]
Sadly no. It was working fine last time. Maybe the solution for getSelectedItemPosition needs just to be exclusively for that method only?

**Comment by smtchahal** [comment]
So just to be clear, it's `position` in `public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {}` that's returning the wrong value, right?

**Comment by peterbetos** [comment]
Yep, that's right ;)

**Comment by smtchahal** [comment]
Please check if this fixes the issue.

**Comment by peterbetos** [comment]
Will test, this can be pulled via jitpack right?

**Comment by smtchahal** [comment]
Yep, just substitute version with the commit hash, so in this case use

```
compile 'com.github.smtchahal:MaterialSpinner:edaab22c53'
```

**Comment by smtchahal** [comment]
`1.1.6-SNAPSHOT` wouldn't work, because I haven't tagged this commit as a release. I'm just following a convention where you append the next version with `-SNAPSHOT` for all commits between two releases.

`com.github.smtchahal:MaterialSpinner:-SNAPSHOT` would work, but it always points to the latest commit. Check out https://jitpack.io for details.

**Comment by peterbetos** [comment]
Yep, noted on that. And the fix worked 👍  Thanks also for creating the other bug for tracking.
