### ISSUE TITLE
Why no spacing between floating label and spinner content?

### ISSUE THREAD

**Issue by filipebezerra** [smtchahal/MaterialSpinner#6]
Why don't you use spacing between the floating label and the spinner content as seen in the image below?

![device-2016-08-01-142751](https://cloud.githubusercontent.com/assets/1006095/17302811/4e9769fe-57f4-11e6-9ea3-72873bf72d4c.png)

I think giving some spacing will be more friendly appearance and delightful to final user as TextInputLayout and EditText have between them:

![device-2016-08-01-143524](https://cloud.githubusercontent.com/assets/1006095/17303008/34c79dea-57f5-11e6-85b0-c4150531631b.png)

**Comment by smtchahal** [comment]
![screen](https://cloud.githubusercontent.com/assets/6754255/17322493/4e879c5a-58bb-11e6-904f-641ac8cb741b.png)

There seems to be enough spacing in the sample app (see screenshot above). Can you post the code you used for the layouts in your screenshots?

**Comment by filipebezerra** [comment]
Hey thanks for your answer. This is my layout setup:

        <smtchahal.materialspinner.MaterialSpinner
            android:id="@+id/spinner"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:ms_multiline="false"
            app:ms_hint="@string/hint"
            app:ms_enableFloatingLabel="true"
            app:ms_floatingLabelText="@string/floating_label"
            />

**Comment by smtchahal** [comment]
@filipebezerra I just tried your code, it still displays the same spacing as in my screenshot above. What version of the library are you using? Did you try using the latest snapshot?

**Comment by smtchahal** [comment]
@filipebezerra Just checked this, the problem exists in version 1.1.6. I just released version 1.1.7 which does not have this problem (and also includes the fix for #5) so please upgrade to that.

Let me know if there's still a problem.

**Comment by filipebezerra** [comment]
@smtchahal upgraded to 1.1.7, issue solved.
